services:
  db:
    container_name: db-local
    image: postgres:16
    ports:
      - 5430:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
  backend-hs:
    container_name: api-server  # コンテナ名を指定
    build: ./api  # api ディレクトリ内の Dockerfile を使う
    depends_on:
      - db
      - redis
    ports:
      - "3100:3100"  # ローカルの 3000 番ポートをコンテナの 8080 番にマッピング
    volumes:
      - ./api:/app  # api ディレクトリをコンテナ内にマウント
    stdin_open: true  # `docker-compose run` の際に `stdin` を開く
    tty: true  # TTY を有効にする（対話的な `bash` 実行を可能にする）
    env_file:
      - .env
